
name: PR-Agent E2E github_app test

on:
  workflow_dispatch:
#  schedule:
#    - cron: '0 0 * * *' # This cron expression runs the workflow every night at midnight UTC


permissions:
  issues: write
  pull-requests: write

jobs:
  pr_agent_job:
    runs-on: ubuntu-latest
    name: PR-Agent E2E github_app test
    steps:
      - name: Run E2E Python Test
        uses: docker://codiumai/pr-agent:github_action
        env:
          OPENAI_KEY: ${{ secrets.OPENAI_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run:
          docker run -e OPENAI_API.API_KEY -e OPENAI_API.ORG_ID -e LOG_SANE=1 --rm codiumai/pr-agent:github_action python tests/e2e_tests/github_app.py


